// BindablePropertyAttribute.cs

namespace SQuan.Helpers.Internals;

/// <summary>
/// An internal attribute used to mark properties for which bindable property code
/// should be generated by the internal source generator.
/// </summary>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
public sealed partial class BindablePropertyAttribute : global::System.Attribute
{
	/// <summary>
	/// Gets or sets a value indicating whether to use the method names specified in the attribute for the generated BindableProperty callbacks.
	/// </summary>
	public bool UseStaticCallbacks { get; set; } = false;

	/// <summary>
	/// Gets the name of the method to invoke when the BindableProperty value changes.
	/// </summary>
	public string? PropertyChangedMethodName { get; set; }

	/// <summary>
	/// Gets the name of the method to invoke when the BindableProperty value is changing, before the value is actually changed.
	/// </summary>
	public string? PropertyChangingMethodName { get; set; }

	/// <summary>
	/// Gets the name of the method to invoke to coerce the BindableProperty value before it's set.
	/// </summary>
	public string? CoerceValueMethodName { get; set; }
}
