// ObservablePropertyAttribute.cs

namespace SQuan.Helpers.Internals;

/// <summary>
/// An internal attribute used to mark properties for which observable property code
/// should be generated by the internal source generator.
/// </summary>
public class ObservablePropertyAttribute : Attribute
{
}
